name: Deploy to azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # enable docker buildkit for faster building
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: stefpiatek
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: stefpiatek/sp_dummy_app:latest
          # cache build steps for faster building
          cache-from: type=registry,ref=stefpiatek/sp_dummy_app:buildcache
          cache-to: type=registry,ref=stefpiatek/sp_dummy_app:buildcache,mode=max
